# Course Materials {-}


Here are the software packages you need to load onto your computer for this course. These programs work on Mac or Windows computers. They are free, safe, and do not take up much disk space. If you already have some of these programs installed, please check to make sure you are using the latest versions.

Before you begin downloading software, please make sure that your operating system (Windows, Linux, or iOS) and browser (Windows Explorer, Firefox, Chrome etc.) are as up-to-date as possible, and that you have installed all the most current patches and updates. The older and more out-of-date your software is, the harder it is to get everything working properly.

Go to each software page and follow the instructions for downloading the installer and running it. The installer will go through a number of steps. Always use the complete installation with the default choices at each step. 

Installing new software can sometimes be tricky. If you run into any issues please contact me or George, and we should be able to help you out.


## Detailed Installation Instructions {-}

Lauren Ash (the original TA for Computational Biology) has graciously provided a much more detailed set of instructions for installing the software that you will need. If you are having any troubles, consult this page

[Lauren's Installation Instructions](Installation_Instructions.html)

## Typora {-}

Typora is a slick little markdown editor that compiles to `.pdf` and `.html`. It is great for learning the markdown language and using for all sorts of basic daily writing activities. 

https://typora.io/

> 2022 Update. It appears that Typora is now charging a fee of $15 for the latest version. This is a one-time fee (not a subscription) with a license for 3 devices. This is an excellent piece of software that I use every day; it is well worth this modest fee.

## Github {-}

GitHub is a free web-based repository for storing and updating your computer code, collaborating with others on documents and coding, and hosting your webpages. We will use GitHub extensively in this course. During the first week of class, you will start by building your own GitHub repository and website, and you will post all of your homeworks and exercises to this website during the semester. It will be an on-line "portfolio" of your work. Register for free GitHub account below, and be sure to record your user name and password for future use.

[register For GitHub](https://github.com/)

## R {-}
R is the basic computational language we will use in this class. We will use R not only for coding, but also for taking notes, displaying code, and creating slides and graphs. The latest version of R (6 January 2024) is 4.3.2 ("Eye Holes").   

[download R](http://lib.stat.cmu.edu/R/CRAN/ )

## RStudio {-}
RStudio is an IDE (Integrated Development Environment), which is a special editor that makes it much easier to use R and adds a number of useful features. **Make sure you have installed/updated R first before you install/update RStudio**. Choose either the Windows or Mac OS installer. The latest version of RStudio (6 January 2024) is RStudio 2023.12.0



[download R Studio](https://www.rstudio.com/products/rstudio/download/)

If you already have R and RStudio installed, you will definitely need to update them so that everything will work properly. Although it is relatively easy to update R, one minor headache is that it does not update all of your packages and libraries, which then have to be reloaded each time you initially use them. Here is an older post post that shows you how to update R and reload all of your previous packages automatically:

https://www.r-bloggers.com/updating-r/

If you have some experience with R already, you may want to try this, although it did not work for me the last time I tried it (04 January 2020). Since then, I have decided it is simpler to just reload the packages I need after a fresh installation. In some cases older packages were defunct, have been upgraded and migrated to CRAN (the official repository for packages), or I am just not using them anymore. So I treat the upgrade of R as a sprimg cleaning, and then just re-install packages as I need them. Please check with me or George if you are having trouble.


Also, you can run into minor snags (especially with `ggplot2`) if your packages have not been updated in a long time. From the console, enter this:

```{r, eval=FALSE}
update.packages(checkBuilt=TRUE, ask=FALSE)
```

## Installing LaTeX and other useful packages {-}
LaTeX (pronounced "la-tech") is a typesetting language that renders plain text to a pdf, and is used by RStudio (and other programs). In the past, getting LaTeX installed properly was a major hair-pulling exercise during the first week of class, particularly for older Windows machines.

Fortunately, life got a lot easier a few years ago with the release of the `tinytex` R package by Yihui Xi. We only need to use this package once to install LaTeX. Two other R packages that we will use frequently are `tidyverse` and `patchwork`. All three packages are now available on CRAN.

If you already know how to install packages in R (either by issuing commands from the original R terminal or through the GUI in RStudio), go ahead and install `tinytex`, `tidyverse`, and `patchwork`. If you don't know how to install R packages, please contact me or George, and we will step you through it.

## Text editors {-}
Plain text files are the common currency of all computational tools, and a plain text editor is also wonderful for composing text without any formatting distractions. Among its many uses, a good plain text editor allows you to search and replace using regular expressions, an incredibly powerful tool. Although there are simple editors that are installed by default on your Mac or Windows machines, they are not true plain text editors and should be avoided. There are many good plain text editors, some free, and some for sale, that you can find for your Mac or Windows machine. In fact, the RStudio itself can function as a simple text editor (although it is not so good for regular expressions, which is what we will be using it for). For this course, download and install one of the following: 


[download Notepad++ for Windows](https://notepad-plus-plus.org/)


[download BBedit for Mac](http://www.barebones.com/products/bbedit/index.html)

The "free" versions of this software will be fine for our use in this course.


## Checking your computer's software {-}

### (This is important for future programs, as well as base R and RStudio)  {-}

**Macs**: Click the apple in the top left of your screen and choose "About This Mac." The latest software to date is Mac OS Big Sur (version 11.1). If you do not have this updated, I strongly suggest you do so before installing R/RStudio. Below the information you can click "Software Update..." and it will lead you to the latest updates, if you have any.

**Windows**: You probably have Windows 8 or 10. To get more information on Windows 10, click the start button and Settings icon. Then, click System and then "About" in the left pane. It will give you information such as whether you have a 32 or 64 bit processor (which is helpful to know for further installation). If you have Windows 8, you can Click "Settings" and then click "Change PC settings" from the sidebar. Then, click "PC and devices," and finally click "PC info."

## Installing R {-}
Follow this link: http://lib.stat.cmu.edu/R/CRAN/ and choose your platform (Windows, Mac, or Linux). The latest version of R (30 December 2022) is 4.1.2 ("Bird Hippie").   

**If you already have R and RStudio installed**, (perhaps from a previous class or you actively use it) verify it is the latest version: it is listed at the top of the console when you open RStudio. If you would like to keep the packages in your library, check out this help page: https://www.r-bloggers.com/2017/05/upgrade-r-without-losing-your-packages/. For RStudio, go to Help -> check for updates.   

**For Windows**, click the "install R for the first time", which is blue and bold next to "base." Then 'Download R 4.1.2 for Windows.' If you download and install with the defaults, it will install both the 32 and 64 bit R versions. You can delete the one that does not match with your processor (see above on how to check that info).

**For Mac**, choose the file that corresponds to your Mac OS X system version. If you have everything up to date, you can download and install 4.1.2 (just click and open the .pkg file).

**For old Macs** (where you cannot update to the latest OS X software):
Go to the same link https://lib.stat.cmu.edu/R/CRAN/ and click “Download for (Mac) OSX”. Scroll down and you will see a list of releases. Choose the .pkg file that corresponds to your software. If you have a version higher than 10.13 (High Sierra), you can choose the latest release.

## Installing RStudio {-}
Go here: https://rstudio.com/products/rstudio/download/#download

* Choose and open the .exe file if you are a **Windows user**
* Choose and open the .dmg file if you are a **Mac user**
* If you have an **old Mac**: here is a list of older versions - https://rstudio.com/products/rstudio/older-versions/


## Installing Rmarkdown in RStudio {-}
* You can have RMarkdown automatically install by going to File -> New File -> RMarkdown... in RStudio. Click yes when it asks whether to install the additional required packages (it may take a couple of minutes for the extra packages associated with Rmarkdown to download). A gray window should pop up asking you to title your new Rmarkdown file. That means Rmarkdown was installed. 
* If it throws an error or gets stuck, restart RStudio and type `install.packages("rmarkdown")` into the Console and press return. If prompted type 'a' (and press return) if it asks which packages to compile and update. If you receive an error, restart RStudio and type 'n'

##### Troubleshooting Rmarkdown: {-}
* Not opening Rmarkdown and stuck on installation of extra packages? Restart RStudio and click "No" when it asks to install packages that require compilation

* stringi error? Type ```install.packages("stringi",type="mac.binary")``` into the console and restart RStudio

* XCode problem ("invalid active developer path")? Manually install XCode using "xcode-select --install" in Terminal. Documentation for the fix here: https://ma.ttias.be/mac-os-xcrun-error-invalid-active-developer-path-missing-xcrun/ 

## Installing LaTex in RStudio {-}
Luckily there is a very nice package that was created for the easy installation of LaTeX in RStudio!     

1. Type ```install.packages("tinytex")``` into the Console and press return to run the code.   
2. After that is complete, type ```tinytex::install_tinytex()``` into the Console and press return. This should take a bit of time depending on the speed of your computer.    

For some reason, even after a successful installation, sometimes it shows some error/warning messages at the end. Ignore them and check whether it works here:

**To check whether it was installed properly**   
1. Go to File -> New File -> RMarkdown...    
2. Then click PDF as the default output option. It will give you example text in the file.   
3. Press the Knit button (with the yarn icon) and name the file whatever you want (Test is always a good option) and put it on your Desktop.   
4. It may take a couple of minutes, but you should have a PDF with the same file name (Test.pdf for example) on your Desktop, if it works.   
5. If it says Error: LaTeX failed to compile, that means the `tinytex` installation did not work. Make sure you ran both lines!  


## Connecting git to RStudio {-}

1) If you have not done so already, you need to download git (you cannot select Version Control in RStudio until it is downloaded) 

* You can download it here: git-scm.com and then restart RStudio

2) When you commit for the first time you will probably receive this message:
`author identity unknown` . We'll need to first introduce you to RStudio and Git with the following instructions.


* You need to set your github email in RStudio (only once when you first commit) using this code (and your own github email and name):  

From RStudio, open the Terminal tab (next to your Console tab), and type this in, filling in your email and username: 
```
git config --global user.email "your.email.edu"
git config --global user.name "Username"
```

3) Creating a Personal Access Token (PAT) on GitHub

* From Github, go to Settings - > Developer Settings - > Personal Access Tokens - > Tokens (classic) - > Generate new token. Copy that token, and then try to commit a change (can be empty) in RStudio. When it asks for your username and password, fill in your username but use that newly generated token as your password instead. 


4) You should now be able to commit changes in RStudio. When you push for the first time it may prompt you to log in (via a pop-up window)  

* You can choose 'authorize on browser,' log in, and click allow access  


#### Troubleshooting GitHub connection {-}

This is particular important to complete if you run into an error stating: "remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.".

If you continue to run into errors or are seeing an error like "Error: Bad Credentials (401)", then you should make sure that you have an updated Personal Access Token with the correct scopes. Here is one option to fix this:

* First create a new PAT with the correct scopes and make sure to copy it. Then, use the "gitcreds" package to set your PAT. To do this, go to your RStudio's Console, type "install.packages("gitcreds")" and then wait for the installation. Once it's installed, type "gitcreds::gitcreds_set()" next. A message should pop up giving you some information about your current credentials. Hit the number corresponding to "Replace these credentials", and then input your fresh PAT and hit enter. 





You may need the following instructions for later, but not for the early part of the course:

```
## Navigating the Shell Lecture 24 (Windows Users)

When you install cygwin, it creates folders wherever you chose to install it; however when you open the cygwin program, it does not automatically have access to your computer root and files  

* You will have to add a 'link' from your computer root to the cygwin folder: do this by typing in the following code (replacing <username> with your Windows user name) and naming the link (in this case it is named Home). A directory will be created where you type this so at the start of your session it will be in your root cygwin folder:  

ln -s "/cygdrive/c/Users/<username>" Home
cd Home
ls

* In this lecture (Lecture 25D Navigating the Shell), the command `r` does not work in cygwin. I believe it needs a path to the R.exe file, so I would advise windows users to skip this.  

Please contact me you are having any additional issues installing these programs: lvash@uvm.edu
```
